// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElSvgIcon: typeof import('./src/components/ElSvgIcon.vue')['default']
    ElSvgItem: typeof import('./src/components/Sidebar/ElSvgItem.vue')['default']
    ImportExportComp: typeof import('./src/components/ImportExportComp.vue')['default']
    LangSelect: typeof import('./src/components/LangSelect/index.vue')['default']
    Link: typeof import('./src/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./src/components/Sidebar/Logo.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFull: typeof import('./src/components/ScreenFull/index.vue')['default']
    ScreenLock: typeof import('./src/components/ScreenLock/index.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/Sidebar/SidebarItem.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
    ThemeSelect: typeof import('./src/components/ThemeSelect/index.vue')['default']
    Tinymce: typeof import('./src/components/Tinymce/index.vue')['default']
  }
}

export {}
