// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColumnFilter: typeof import('./../src/components/ColumnFilter.vue')['default']
    DictTag: typeof import('./../src/components/DictTag.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    InnerLink: typeof import('./../src/components/InnerLink/index.vue')['default']
    JsonInput: typeof import('./../src/components/JsonInput.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/index.vue')['default']
    ParentView: typeof import('./../src/components/ParentView/index.vue')['default']
    RightToolbar: typeof import('./../src/components/RightToolbar/index.vue')['default']
    RightToolBar: typeof import('./../src/components/RightToolBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    TestUnit: typeof import('./../src/components/TestUnit.vue')['default']
  }
}
