#!/bin/sh
#. "$(dirname "$0")/_/husky.sh"
#yarn run lint
#npx --no-install commitlint --edit "$1"
#npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'
#推送之前运行eslint检查
yarn run lint || echo exit;
